### ISSUE TITLE
Zold commands fail after launching node for the first time

### ISSUE THREAD

**Issue by biboran** [yegor256/zold#76]
After running `zold node --invoice 45fc3916b5274ed1 --threads 1` successfully, other commands now fail with the same error even if I stop the node. Here is a sample output for `zold --trace show`:
```
ERROR: invalid value for Integer(): "0x.v8flags.6.6.346.24-node.5.82027888c5bb8fc395411cb6804a066c.json" (ArgumentError)
/usr/local/lib/ruby/gems/2.5.0/gems/zold-0.9.8/lib/zold/id.rb:33:in `Integer'
/usr/local/lib/ruby/gems/2.5.0/gems/zold-0.9.8/lib/zold/id.rb:33:in `initialize'
/usr/local/lib/ruby/gems/2.5.0/gems/zold-0.9.8/lib/zold/wallets.rb:54:in `new'
/usr/local/lib/ruby/gems/2.5.0/gems/zold-0.9.8/lib/zold/wallets.rb:54:in `block in all'
/usr/local/lib/ruby/gems/2.5.0/gems/zold-0.9.8/lib/zold/wallets.rb:49:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/zold-0.9.8/lib/zold/wallets.rb:49:in `select'
/usr/local/lib/ruby/gems/2.5.0/gems/zold-0.9.8/lib/zold/wallets.rb:49:in `all'
/usr/local/lib/ruby/gems/2.5.0/gems/zold-0.9.8/lib/zold/commands/fetch.rb:59:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/zold-0.9.8/bin/zold:145:in `<top (required)>'
/usr/local/bin/zold:23:in `load'
/usr/local/bin/zold:23:in `<main>'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.9.9`

**Comment by yegor256** [comment]
@biboran try 0.9.9, the problem should disappear

**Comment by biboran** [comment]
@yegor256 seems to be working

**Comment by 0crat** [comment]
I'm not managing `yegor256/zold` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)
