### ISSUE TITLE
No such file or directory in "copies.rb"

### ISSUE THREAD

**Issue by yegor256** [yegor256/zold#92]
```
No such file or directory @ rb_sysopen - zold-node/zold-copies/0000000000000000/10
	/var/lib/gems/2.3.0/gems/zold-0.9.11/lib/zold/copies.rb:66:in `read'
	/var/lib/gems/2.3.0/gems/zold-0.9.11/lib/zold/copies.rb:66:in `block in add'
	/var/lib/gems/2.3.0/gems/zold-0.9.11/lib/zold/copies.rb:66:in `each'
	/var/lib/gems/2.3.0/gems/zold-0.9.11/lib/zold/copies.rb:66:in `find'
	/var/lib/gems/2.3.0/gems/zold-0.9.11/lib/zold/copies.rb:66:in `add'
	/var/lib/gems/2.3.0/gems/zold-0.9.11/lib/zold/node/entrance.rb:74:in `push_unsafe'
	/var/lib/gems/2.3.0/gems/zold-0.9.11/lib/zold/node/entrance.rb:53:in `block in push'
	/var/lib/gems/2.3.0/gems/zold-0.9.11/lib/zold/node/entrance.rb:52:in `synchronize'
	/var/lib/gems/2.3.0/gems/zold-0.9.11/lib/zold/node/entrance.rb:52:in `push'
	/var/lib/gems/2.3.0/gems/zold-0.9.11/lib/zold/node/front.rb:123:in `block in <class:Front>'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.10.4`

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
