### ISSUE TITLE
File is absent in wallet.rb

### ISSUE THREAD

**Issue by yegor256** [yegor256/zold#93]
```
File 'zold-node/zold-copies/0000000000000000/../0000000000000000/10' is absent
	/var/lib/gems/2.3.0/gems/zold-0.10.4/lib/zold/wallet.rb:162:in `lines'
	/var/lib/gems/2.3.0/gems/zold-0.10.4/lib/zold/wallet.rb:59:in `network'
	/var/lib/gems/2.3.0/gems/zold-0.10.4/lib/zold/patch.rb:40:in `join'
	/var/lib/gems/2.3.0/gems/zold-0.10.4/lib/zold/commands/merge.rb:68:in `block in merge'
	/var/lib/gems/2.3.0/gems/zold-0.10.4/lib/zold/commands/merge.rb:67:in `each'
	/var/lib/gems/2.3.0/gems/zold-0.10.4/lib/zold/commands/merge.rb:67:in `merge'
	/var/lib/gems/2.3.0/gems/zold-0.10.4/lib/zold/commands/merge.rb:54:in `block in run'
	/var/lib/gems/2.3.0/gems/zold-0.10.4/lib/zold/commands/merge.rb:52:in `each'
	/var/lib/gems/2.3.0/gems/zold-0.10.4/lib/zold/commands/merge.rb:52:in `run'
	/var/lib/gems/2.3.0/gems/zold-0.10.4/lib/zold/node/entrance.rb:80:in `push_unsafe'
	/var/lib/gems/2.3.0/gems/zold-0.10.4/lib/zold/node/entrance.rb:53:in `block in push'
	/var/lib/gems/2.3.0/gems/zold-0.10.4/lib/zold/node/entrance.rb:52:in `synchronize'
	/var/lib/gems/2.3.0/gems/zold-0.10.4/lib/zold/node/entrance.rb:52:in `push'
	/var/lib/gems/2.3.0/gems/zold-0.10.4/lib/zold/node/front.rb:124:in `block in <class:Front>'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.10.5`

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
