### ISSUE TITLE
NPE in copies

### ISSUE THREAD

**Issue by yegor256** [yegor256/zold#94]
```
undefined method `map' for nil:NilClass
Did you mean?  tap
	/app/lib/zold/copies.rb:123:in `save'
	/app/lib/zold/copies.rb:53:in `remove'
	/app/lib/zold/node/entrance.rb:82:in `push_unsafe'
	/app/lib/zold/node/entrance.rb:53:in `block in push'
	/app/lib/zold/node/entrance.rb:52:in `synchronize'
	/app/lib/zold/node/entrance.rb:52:in `push'
	/app/lib/zold/node/front.rb:124:in `block in <class:Front>'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.10.7`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@24b34ee2-112b-48ac-b25b-4b5b5639b958, thread: pool-1715-thread-1
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "roles.xml" in "C91QJT4CF" in 1min: 442e17af4e0c/4hr/0/0/false/false by QuartzScheduler_Worker-3
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: yegor256/zold#94, Action: `opened`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@24b34ee2-112b-48ac-b25b-4b5b5639b958, thread: pool-1788-thread-1
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "claims.xml" in "C91QJT4CF" in 1min: 442e17af4e0c/4hr/0/0/false/false by QuartzScheduler_Worker-3
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: yegor256/zold#94, Action: `closed`
